/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "background": "#111318",
        "on-secondary": "#1a3055",
        "primary": "#acc7ff",
        "surface-tint": "#acc7ff",
        "on-tertiary-fixed": "#2d1600",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e2e2e9",
        "inverse-on-surface": "#2e3036",
        "error": "#ffb4ab",
        "secondary": "#b2c7f5",
        "surface-container-highest": "#33353a",
        "secondary-container": "#344970",
        "on-background": "#e2e2e9",
        "on-secondary-container": "#a4b8e6",
        "surface-dim": "#111318",
        "secondary-fixed": "#d7e2ff",
        "inverse-primary": "#005bbf",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#b2c7f5",
        "tertiary": "#ffb873",
        "surface-container-lowest": "#0c0e13",
        "on-primary": "#002f68",
        "on-primary-fixed": "#001a40",
        "primary-container": "#508ff8",
        "on-tertiary": "#4b2800",
        "on-surface-variant": "#c2c6d5",
        "surface": "#111318",
        "surface-variant": "#33353a",
        "outline-variant": "#424753",
        "on-primary-container": "#00285b",
        "surface-bright": "#37393f",
        "on-surface": "#e2e2e9",
        "tertiary-container": "#d37b02",
        "on-error": "#690005",
        "outline": "#8c909e",
        "primary-fixed-dim": "#acc7ff",
        "surface-container-low": "#1a1b21",
        "on-primary-fixed-variant": "#004492",
        "on-tertiary-fixed-variant": "#6a3b00",
        "on-secondary-fixed-variant": "#32476d",
        "tertiary-fixed-dim": "#ffb873",
        "on-tertiary-container": "#412200",
        "surface-container-high": "#282a2f",
        "tertiary-fixed": "#ffdcbf",
        "surface-container": "#1e1f25",
        "primary-fixed": "#d7e2ff",
        "on-secondary-fixed": "#011a3f"
      },
      fontFamily: {
        "headline": ["Instrument Serif", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
